#ifndef MAIN_IOT_SERVER_CONFIG_H_
#define MAIN_IOT_SERVER_CONFIG_H_

#define IOT_SERVER_SCHEME "http"
#define IOT_SERVER_HOST   "127.0.0.1"
#define IOT_SERVER_PORT   ""

#define IOT_BASE_PATH    "/iot"
#define IOT_PROJECT_PATH "/hexagons"
#define IOT_LOGS_PATH    "/logs"

#define OTA_MANIFEST_FILE "manifest.json"
#define OTA_FIRMWARE_FILE "firmware.bin"
#define OTA_LOG_FILE      "ota_log.php"

#define IOT_SERVER_BASE_URL IOT_SERVER_SCHEME "://" IOT_SERVER_HOST IOT_SERVER_PORT IOT_BASE_PATH
#define IOT_OTA_LOG_URL     IOT_SERVER_BASE_URL IOT_LOGS_PATH "/" OTA_LOG_FILE

#define OTA_MANIFEST_URL IOT_SERVER_BASE_URL IOT_PROJECT_PATH "/" OTA_MANIFEST_FILE
#define OTA_FIRMWARE_URL IOT_SERVER_BASE_URL IOT_PROJECT_PATH "/" OTA_FIRMWARE_FILE

#endif